apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: homepage-config
    namespace: homepage

    files:
      - config/settings.yaml
      - config/services.yaml
      - config/bookmarks.yaml
      - config/widgets.yaml
      - config/kubernetes.yaml
      - config/docker.yaml
      - config/custom.css
      - config/custom.js

generatorOptions:
  labels:
    app.kubernetes.io/name: homepage