
apiVersion: v1
kind: PersistentVolume

metadata:
  name: media-movies

spec:
  capacity:
    storage: 2Ti

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: ""

  mountOptions:
    - nfsvers=4.1

  nfs:
    server: 172.16.0.2
    path: /mnt/main/media

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: media-movies
  namespace: media

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: ""

  volumeName: media-movies

  resources:
    requests:
      storage: 2Ti