prometheus:
  additionalPodMonitors:
    - name: flux-system

      namespaceSelector:
        matchNames:
          - flux-system

      selector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - source-controller
              - kustomize-controller
              - helm-controller
              - notification-controller

      podMetricsEndpoints:
        - port: http-prom
          path: /metrics
          interval: 30s

          relabelings:
            - sourceLabels:
                - __meta_kubernetes_pod_phase
              action: keep
              regex: Running

kube-state-metrics:
  rbac:
    extraRules:
      - apiGroups:
          - source.toolkit.fluxcd.io
          - kustomize.toolkit.fluxcd.io
          - helm.toolkit.fluxcd.io

        resources:
          - gitrepositories
          - helmrepositories
          - kustomizations
          - helmreleases

        verbs:
          - list
          - watch

  customResourceState:
    enabled: true

    config:
      spec:
        resources:
          - groupVersionKind:
              group: kustomize.toolkit.fluxcd.io
              version: v1
              kind: Kustomization

            metricNamePrefix: gotk

            metrics:
              - name: resource_info
                help: The current state of a Flux Kustomization resource.

                each:
                  type: Info

                  info:
                    labelsFromPath:
                      name:
                        - metadata
                        - name

                labelsFromPath:
                  exported_namespace:
                    - metadata
                    - namespace

                  ready:
                    - status
                    - conditions
                    - "[type=Ready]"
                    - status

                  suspended:
                    - spec
                    - suspend

                  revision:
                    - status
                    - lastAppliedRevision

                  source_name:
                    - spec
                    - sourceRef
                    - name

          - groupVersionKind:
              group: helm.toolkit.fluxcd.io
              version: v2
              kind: HelmRelease

            metricNamePrefix: gotk

            metrics:
              - name: resource_info
                help: The current state of a Flux HelmRelease resource.

                each:
                  type: Info

                  info:
                    labelsFromPath:
                      name:
                        - metadata
                        - name

                labelsFromPath:
                  exported_namespace:
                    - metadata
                    - namespace

                  ready:
                    - status
                    - conditions
                    - "[type=Ready]"
                    - status

                  suspended:
                    - spec
                    - suspend

                  revision:
                    - status
                    - history
                    - "0"
                    - chartVersion

                  chart_name:
                    - status
                    - history
                    - "0"
                    - chartName

                  chart_app_version:
                    - status
                    - history
                    - "0"
                    - appVersion

          - groupVersionKind:
              group: source.toolkit.fluxcd.io
              version: v1
              kind: GitRepository

            metricNamePrefix: gotk

            metrics:
              - name: resource_info
                help: The current state of a Flux GitRepository resource.

                each:
                  type: Info

                  info:
                    labelsFromPath:
                      name:
                        - metadata
                        - name

                labelsFromPath:
                  exported_namespace:
                    - metadata
                    - namespace

                  ready:
                    - status
                    - conditions
                    - "[type=Ready]"
                    - status

                  suspended:
                    - spec
                    - suspend

                  revision:
                    - status
                    - artifact
                    - revision

                  url:
                    - spec
                    - url

          - groupVersionKind:
              group: source.toolkit.fluxcd.io
              version: v1
              kind: HelmRepository

            metricNamePrefix: gotk

            metrics:
              - name: resource_info
                help: The current state of a Flux HelmRepository resource.

                each:
                  type: Info

                  info:
                    labelsFromPath:
                      name:
                        - metadata
                        - name

                labelsFromPath:
                  exported_namespace:
                    - metadata
                    - namespace

                  ready:
                    - status
                    - conditions
                    - "[type=Ready]"
                    - status

                  suspended:
                    - spec
                    - suspend

                  revision:
                    - status
                    - artifact
                    - revision

                  url:
                    - spec
                    - url