apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-data
  namespace: finance
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: truenas-nfs

  resources:
    requests:
      storage: 10Gi