apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ad4QTXOemD9DuS4Oc9cml/sQ2C0F098ue82sFXbUj+OywJ2syeQ/wTFeL6qgkU/A2QAp4Xo=,iv:H/8Htvo4vn+xQ1jzD9kUwseWxNvaQhpE8/o8obvhEks=,tag:A1bgQytH7sGxa3BMNelRFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdVY2THlraUpiTVFBTXJy
            bzJUbng0bWZTeUhLY3lGZFhKYzNEZU8rUjBjCmwwTXdjQlhYMkdOZGJUQmNCc2hU
            RHZMSldKWmszZ1pFOExjcmh1Mi9DdDQKLS0tIEZmUm03U1RBT0tXYkd2SEQ5cE1l
            a1gydnlBa3QzRmVmem9ya2VrRWVRdmcK++H+CnuRSM53e0c9QGz5X6+OHgCNxHvZ
            4phAhRRDHpuWbjdEH0xd8ZMfbL5Y0ukKXBEgZx84yFv2c6QlKDjRRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13qjestjfa60raw5g053fgg6502309kdaecrsla0njpktvp0ggy7sreq4uz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T14:54:47Z"
    mac: ENC[AES256_GCM,data:lUJP7O4MM1YE7bzwGKnKD595cbRTkZw7R8iRwHNhfGEkj5nHxU6iTuYoMAabUckaASbB1VkC/wvSrUz0dzWlceVKeQIrv+ieVJTXWuJfnMhLwRPjQuGOIjPrwwMoW0+HrSf6hQjx5Y4zx3plu5qifMEKOTHdhCzjQBI4LcLZzBg=,iv:JiBrEkKQNH+giHV7fAcSMPd3ZKPAQzdQZDpAMZSCuJM=,tag:R8JTxdvI3B5+Lq18B8Sinw==,type:str]
    version: 3.13.3
